platform :ios, '7.0'

target 'Zhongche-ios-driver’ do
  pod 'AFNetworking'
  pod 'SDWebImage', '~>3'
  pod 'SVProgressHUD'
  pod 'YYModel'
  pod 'MJRefresh'
  pod 'XHImageViewer'
  pod 'AMap3DMap'
  pod 'AMapSearch'
  pod 'YYModel'
  pod 'ReactiveCocoa'
  pod 'AFNetworking-RACRetryExtensions'
  pod 'SDVersion'
  pod 'FMDB','~>2.6.2'
  pod 'UMengAnalytics'
  pod 'GTSDK'

end

